# Generated by Django 5.2.1 on 2025-06-04 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclass',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.clubclass'),
        ),
        migrations.AddField(
            model_name='messageclass',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files'),
        ),
        migrations.AddField(
            model_name='messageclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images'),
        ),
        migrations.AddField(
            model_name='messageclass',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageclass',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageclass',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
