# Generated by Django 5.2.1 on 2025-06-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
