# Generated by Django 5.2.1 on 2025-06-21 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubclass_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ManyToManyField(to='club.clubclass')),
                ('requester', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
