# Generated by Django 5.2.1 on 2025-06-21 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_clubrequestmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrequestmodel',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubrequestmodel',
            name='requester',
        ),
        migrations.AddField(
            model_name='clubrequestmodel',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='club.clubclass'),
        ),
        migrations.AddField(
            model_name='clubrequestmodel',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
